name: CI

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'doc/oper-guide/**'
      - 'CREDITS'
      - 'LICENSE'
      - 'NEWS.md'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/oper-guide/**'
      - 'CREDITS'
      - 'LICENSE'
      - 'NEWS.md'
      - 'README.md'

jobs:
  linux:
    name: Linux

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Debian 10 Buster
          - os: ubuntu-20.04
            compiler: gcc-8
          - os: ubuntu-20.04
            compiler: clang-7
          # Ubuntu 20.04 Focal
          - os: ubuntu-20.04
            compiler: gcc-9
          - os: ubuntu-20.04
            compiler: clang-10
          # Debian 11 Bullseye
          - os: ubuntu-22.04
            compiler: gcc-10
          - os: ubuntu-22.04
            compiler: clang-11
          # Ubuntu 22.04 Jammy
          - os: ubuntu-22.04
            compiler: gcc-11
          - os: ubuntu-22.04
            compiler: clang-14
          # next
          - os: ubuntu-22.04
            compiler: gcc-12

    env:
      CC: ${{ matrix.compiler }}

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ${CC} \
          automake \
          autoconf \
          libtool \
          libsqlite3-dev \
          libhyperscan-dev \
          # EOF
    - uses: actions/checkout@v2
    - name: autogen.sh
      run: bash autogen.sh
    - name: configure
      run: CFLAGS="-Werror -Wno-unused-value -Wno-unused-parameter" ./configure --enable-assert=hard --enable-warnings
    - name: make
      run: make -j2
    - name: make check
      run: make check
    - name: make install
      run: make install
